### ISSUE TITLE
too small font-size

### ISSUE THREAD

**Issue by ghost** [hhpr98/TKGD2019_N12#3]
1. `header-top`:
![image](https://user-images.githubusercontent.com/52388146/70867459-a64a3980-1f6d-11ea-9c55-741293653ccd.png)

2. `category` and `rating`:
![image](https://user-images.githubusercontent.com/52388146/70867481-da255f00-1f6d-11ea-81ff-0625d9033d79.png)

**Comment by hhpr98** [comment]
để thế này là ổn, cái này add on thêm thôi
