### ISSUE TITLE
Bỏ sản phẩm nổi bật, thêm các chứng nhận ở footer

### ISSUE THREAD

**Issue by hhpr98** [hhpr98/TKGD2019_N12#8]

**Comment by ghost** [comment]
> thêm các chứng nhận ở footer

Dấu xác nhận của **Bộ Công Thương**?
![image](https://user-images.githubusercontent.com/52388146/70909712-f379ea00-2005-11ea-9fed-c5f61f2f5780.png)

**Comment by hhpr98** [comment]
giải thưởng sao vàng, mai vàng gì đó cũng đc..
